// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**  Opens the settings window, or focuses it if it is already open. */
	openSettings: () => __TAURI_INVOKE<void>("open_settings"),
	alwaysOnTop: () => __TAURI_INVOKE<boolean>("always_on_top"),
	setAlwaysOnTop: (enabled: boolean) => __TAURI_INVOKE<void>("set_always_on_top", { enabled }),
	/**  Hides the companion to the tray. */
	hideCompanion: () => __TAURI_INVOKE<void>("hide_companion"),
	setClickThrough: (enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_click_through", { enabled })),
	/**  Multiplies the companion's size by `factor`; the result is clamped to the allowed range. */
	scaleCompanion: (factor: number | null) => typedError<null, AppError>(__TAURI_INVOKE("scale_companion", { factor })),
	/**  The saved framing for `character`, or `None` if the user never adjusted it. */
	characterFraming: (character: string) => typedError<{
	/**  How many window heights the model canvas spans; 1 fits it exactly. */
	zoom: number | null,
	/**
	 *  The model-space point shown at the window's centre. Older files have no `centerX`;
	 *  0 is the canvas centre, where models are normally drawn.
	 */
	centerX?: number | null,
	centerY: number | null,
} | null, AppError>(__TAURI_INVOKE("character_framing", { character })),
	/**  Saves `framing` for `character`, clamped to the allowed range. */
	saveCharacterFraming: (character: string, framing: Framing) => typedError<null, AppError>(__TAURI_INVOKE("save_character_framing", { character, framing })),
	/**  Forgets the saved framing for `character`, so the model's default applies again. */
	clearCharacterFraming: (character: string) => typedError<null, AppError>(__TAURI_INVOKE("clear_character_framing", { character })),
	/**  The installed characters, by name. */
	listCharacters: () => typedError<CharacterSummary[], AppError>(__TAURI_INVOKE("list_characters")),
	/**  The character the companion shows, or `None` if no character is active. */
	activeCharacter: () => typedError<{
	id: string,
	/**  The `model3.json`, served by the `character` URI scheme. */
	modelUrl: string,
	extras: ModelExtras,
} | null, AppError>(__TAURI_INVOKE("active_character")),
	/**  Switches the companion to an installed character, or to none. */
	setActiveCharacter: (id: string | null) => typedError<null, AppError>(__TAURI_INVOKE("set_active_character", { id })),
	/**  Deletes an installed character and its saved preferences. */
	removeCharacter: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("remove_character", { id })),
	/**
	 *  Gives an installed character a display name, or with `None` (or a blank name) goes
	 *  back to the pack's name.
	 */
	renameCharacter: (id: string, name: string | null) => typedError<null, AppError>(__TAURI_INVOKE("rename_character", { id, name })),
	/**  Marks an installed character as a favourite, or unmarks it. */
	setCharacterFavorite: (id: string, favorite: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_character_favorite", { id, favorite })),
	/**
	 *  Lets the user pick a pack or model, then copies and validates it in staging. `None` if
	 *  the dialog was cancelled.
	 */
	stageCharacterImport: (kind: ImportKind) => typedError<{
	token: string,
	character: CharacterSummary,
	modelUrl: string,
	extras: ModelExtras,
	warnings: string[],
} | null, AppError>(__TAURI_INVOKE("stage_character_import", { kind })),
	/**  Checks a staged import against the manifest the webview built from its model. */
	reviewCharacterImport: (token: string, manifest: ModelManifest) => typedError<ImportReview, AppError>(__TAURI_INVOKE("review_character_import", { token, manifest })),
	/**
	 *  Installs a reviewed import under `name` and makes it active. `replace` allows replacing
	 *  an installed character with the same id.
	 */
	commitCharacterImport: (token: string, replace: boolean, name: string) => typedError<null, AppError>(__TAURI_INVOKE("commit_character_import", { token, replace, name })),
	/**  Discards a staged import. */
	cancelCharacterImport: (token: string) => typedError<null, AppError>(__TAURI_INVOKE("cancel_character_import", { token })),
};

/** Events */
export const events = {
	activeCharacterChanged: makeEvent<ActiveCharacterChanged>("active-character-changed"),
	alwaysOnTopChanged: makeEvent<AlwaysOnTopChanged>("always-on-top-changed"),
	charactersChanged: makeEvent<CharactersChanged>("characters-changed"),
	cursorMoved: makeEvent<CursorMoved>("cursor-moved"),
	resetFraming: makeEvent<ResetFraming>("reset-framing"),
};

/* Types */
/**  What the companion needs to load the active character. */
export type ActiveCharacter = {
	id: string,
	/**  The `model3.json`, served by the `character` URI scheme. */
	modelUrl: string,
	extras: ModelExtras,
};

/**  The active character changed, was replaced by a re-import, or was removed (`None`). */
export type ActiveCharacterChanged = {
	character: ActiveCharacter | null,
};

/**  The companion's always-on-top setting changed, from the tray or the companion menu. */
export type AlwaysOnTopChanged = {
	alwaysOnTop: boolean,
};

/**
 *  The one error type that crosses IPC. Module errors convert into it at the command
 *  boundary; messages must never carry secrets.
 */
export type AppError = { kind: "invalidArgument"; message: string } | { kind: "window"; message: string } | { kind: "character"; message: string };

export type AppInfo = {
	name: string,
	version: string,
};

/**  An installed character, as listed in the settings window. */
export type CharacterSummary = {
	id: string,
	/**  The user's alias if there is one, else the pack's name (D44). */
	name: string,
	/**  The name in the pack's `character.json`. */
	packName: string,
	favorite: boolean,
	author: string,
	license: string,
	iconUrl: string | null,
};

/**  A character was installed or removed. */
export type CharactersChanged = null;

/**
 *  The global cursor, relative to the companion's client area in CSS pixels. Values outside
 *  the window's size mean the cursor is elsewhere on the desktop.
 */
export type CursorMoved = {
	x: number | null,
	y: number | null,
};

export type ExtraExpression = {
	name: string,
	file: string,
};

export type ExtraMotion = {
	file: string,
};

export type ExtraMotionGroup = {
	name: string,
	motions: ExtraMotion[],
};

/**
 *  Which part of the model fills the companion window, in model units (the model canvas is
 *  2 units tall, centred on the origin). Independent of the window's size.
 */
export type Framing = {
	/**  How many window heights the model canvas spans; 1 fits it exactly. */
	zoom: number | null,
	/**
	 *  The model-space point shown at the window's centre. Older files have no `centerX`;
	 *  0 is the canvas centre, where models are normally drawn.
	 */
	centerX?: number | null,
	centerY: number | null,
};

export type HitAreaInfo = {
	id: string,
	name: string,
};

/**  What to pick in the native dialog. */
export type ImportKind = 
/**  A pack folder or a model folder. */
"folder" | 
/**  A `.zip` or a `.model3.json`. */
"file";

/**  What the user confirms before an import is installed. */
export type ImportReview = {
	warnings: string[],
	/**  The name of the installed character this import would replace. */
	replaces: string | null,
	/**
	 *  The name to offer for the character: the replaced one's alias if it has one, so
	 *  replacing keeps it, else the pack's name.
	 */
	name: string,
};

/**
 *  Expressions and motions that ship with a model but are missing from its `model3.json`,
 *  typical of VTube Studio exports. The loader merges them into the parsed `model3.json`,
 *  so the Live2D export itself stays untouched. Paths are relative to the `model3.json`.
 */
export type ModelExtras = {
	expressions: ExtraExpression[],
	motionGroups: ExtraMotionGroup[],
};

export type ModelManifest = {
	/**  In moc order. */
	parameters: ParameterInfo[],
	expressions: string[],
	motionGroups: MotionGroupInfo[],
	hitAreas: HitAreaInfo[],
	standardParameters: string[],
	eyeBlinkIds: string[],
	lipSyncIds: string[],
};

export type MotionGroupInfo = {
	name: string,
	motions: string[],
};

export type ParameterInfo = {
	id: string,
	min: number | null,
	max: number | null,
	default: number | null,
	/**  Display name from `cdi3.json`, when the model ships one. */
	name?: string | null,
};

/**
 *  The user asked to reset the companion (tray menu): restore the model's default framing
 *  and forget the saved one.
 */
export type ResetFraming = null;

/**  A pack copied into staging and validated, waiting for the webview to build its manifest. */
export type StagedImport = {
	token: string,
	character: CharacterSummary,
	modelUrl: string,
	extras: ModelExtras,
	warnings: string[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

