// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**  Opens the settings window, or focuses it if it is already open. */
	openSettings: () => __TAURI_INVOKE<void>("open_settings"),
	alwaysOnTop: () => __TAURI_INVOKE<boolean>("always_on_top"),
	setAlwaysOnTop: (enabled: boolean) => __TAURI_INVOKE<void>("set_always_on_top", { enabled }),
	/**  Hides the companion to the tray. */
	hideCompanion: () => __TAURI_INVOKE<void>("hide_companion"),
	setClickThrough: (enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_click_through", { enabled })),
	/**  Multiplies the companion's size by `factor`; the result is clamped to the allowed range. */
	scaleCompanion: (factor: number | null) => typedError<null, AppError>(__TAURI_INVOKE("scale_companion", { factor })),
	/**  The saved framing for `character`, or `None` if the user never adjusted it. */
	characterFraming: (character: string) => typedError<{
	/**  How many window heights the model canvas spans; 1 fits it exactly. */
	zoom: number | null,
	/**
	 *  The model-space point shown at the window's centre. Older files have no `centerX`;
	 *  0 is the canvas centre, where models are normally drawn.
	 */
	centerX?: number | null,
	centerY: number | null,
} | null, AppError>(__TAURI_INVOKE("character_framing", { character })),
	/**  Saves `framing` for `character`, clamped to the allowed range. */
	saveCharacterFraming: (character: string, framing: Framing) => typedError<null, AppError>(__TAURI_INVOKE("save_character_framing", { character, framing })),
	/**  Forgets the saved framing for `character`, so the model's default applies again. */
	clearCharacterFraming: (character: string) => typedError<null, AppError>(__TAURI_INVOKE("clear_character_framing", { character })),
};

/** Events */
export const events = {
	alwaysOnTopChanged: makeEvent<AlwaysOnTopChanged>("always-on-top-changed"),
	cursorMoved: makeEvent<CursorMoved>("cursor-moved"),
	resetFraming: makeEvent<ResetFraming>("reset-framing"),
};

/* Types */
/**  The companion's always-on-top setting changed, from the tray or the companion menu. */
export type AlwaysOnTopChanged = {
	alwaysOnTop: boolean,
};

/**
 *  The one error type that crosses IPC. Module errors convert into it at the command
 *  boundary; messages must never carry secrets.
 */
export type AppError = { kind: "invalidArgument"; message: string } | { kind: "window"; message: string };

export type AppInfo = {
	name: string,
	version: string,
};

/**
 *  The global cursor, relative to the companion's client area in CSS pixels. Values outside
 *  the window's size mean the cursor is elsewhere on the desktop.
 */
export type CursorMoved = {
	x: number | null,
	y: number | null,
};

/**
 *  Which part of the model fills the companion window, in model units (the model canvas is
 *  2 units tall, centred on the origin). Independent of the window's size.
 */
export type Framing = {
	/**  How many window heights the model canvas spans; 1 fits it exactly. */
	zoom: number | null,
	/**
	 *  The model-space point shown at the window's centre. Older files have no `centerX`;
	 *  0 is the canvas centre, where models are normally drawn.
	 */
	centerX?: number | null,
	centerY: number | null,
};

/**
 *  The user asked to reset the companion (tray menu): restore the model's default framing
 *  and forget the saved one.
 */
export type ResetFraming = null;

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

