// The only module allowed to talk to the Rust core. `bindings.ts` is generated by
// `cargo test` in src-tauri/ (see `export_bindings` in lib.rs); do not edit it by hand.
// Wrapped bindings are exported through their wrappers rather than raw.
export { type AppError, type AppInfo, commands } from "./bindings";
export * from "./companion";
export * from "./window";
