// The only module allowed to talk to the Rust core. `bindings.ts` is generated by
// `cargo test` in src-tauri/ (see `export_bindings` in lib.rs); do not edit it by hand.
export * from "./bindings";
